# Site settings
title: Jenn Dodd
email: dodd.jl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The personal website and blog of Jenn Dodd.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jenndodd
github_username:  jenndodd
linkedin_username: jenndodd
dribbble_username: jenndodd
permalink: /blog/:title

# Build settings
markdown: kramdown

gems:
  - jemoji
